services:
  currency:
    build: ./
    command: ./cron
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CONFIG_PATH: ${CONFIG_PATH}

  database:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 6s
      timeout: 6s
      retries: 10
    ports:
      - 5432:5432
volumes:
  pgdata: