services:

  currency:
    build:
      context: .
      dockerfile: currency/Dockerfile
    command: ./cronApp --config=./currency/configs
    ports:
      - 8081:8081
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_NAME: ${CURRENCY_DB_NAME}
      DB_USER: ${CURRENCY_DB_USER}
      DB_PASSWORD: ${CURRENCY_DB_PASSWORD}
      DB_HOST: ${CURRENCY_DB_HOST}
      DB_PORT: ${CURRENCY_DB_PORT}
      DB_SSLMODE: ${CURRENCY_DB_SSLMODE}
      DB_DIR_MIGRATIONS: ${CURRENCY_DB_DIR_MIGRATIONS}


  database:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${CURRENCY_DB_PASSWORD}
      POSTGRES_USER: ${CURRENCY_DB_USER}
      POSTGRES_DB: ${CURRENCY_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 6s
      timeout: 6s
      retries: 10
    ports:
      - 5432:5432
    command: postgres -c listen_addresses='*'

  auth-generator:
    image: andrianovartemii/gm-test-task-auth-generator:latest
    ports:
      - 8080:8080
    environment:
      AUTH_TOKEN_LIFETIME: 2

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    command: ./gatewayApp --config=./gateway/configs
    ports:
      - 8082:8082

volumes:
  pgdata: